# Generated by Django 5.2.1 on 2025-06-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="likes",
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
