# Generated by Django 5.2.1 on 2025-06-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_notes_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="likes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
