# Generated by Django 5.2.1 on 2025-06-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_notes_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
